<li>
							<div class="news_pic col-lg-3 col-md-3 col-sm-4 col-xs-12">									
								<a href="[field:arcurl/]" class="">
									[field:image/]
								</a>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
								<a href="[field:arcurl/]" class="news_tit">[field:title/]</a>
								<p class="news_time">[field:pubdate function="GetDateMK(@me)"/]</p>
								<p class="news_desc">[field:description/]...</p>
							</div>
						</li>