<?php
$z[0]=Array("global","",216,243);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\">[field:typename /]</a></li>",675,769);
$z[1][4]['typeid']="3";
$z[2]=Array("type","<li><a href=\"[field:typelink /]\">[field:typename /]</a></li>",778,872);
$z[2][4]['typeid']="2";
$z[3]=Array("type","<li><a href=\"[field:typelink /]\">[field:typename /]</a></li>",881,975);
$z[3][4]['typeid']="5";
$z[4]=Array("type","<li><a href=\"[field:typelink /]\">[field:typename /]</a></li>",984,1078);
$z[4][4]['typeid']="4";

?>