<?php
$z[0]=Array("global","",61,88);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",119,146);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",269,296);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("type","<li class=\"on_1\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",325,432);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<li class=\"on_2\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",444,551);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<li class=\"on_3\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",563,670);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<li class=\"on_4\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",682,789);
$z[6][4]['typeid']="4";
$z[7]=Array("type","<li class=\"on_5\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",801,908);
$z[7][4]['typeid']="5";
$z[8]=Array("global","",1028,1055);
$z[8][4]['name']="cfg_basehost";
$z[9]=Array("global","",1087,1114);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",1225,1252);
$z[10][4]['name']="cfg_basehost";
$z[11]=Array("type","<li class=\"on_1\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1281,1388);
$z[11][4]['typeid']="1";
$z[12]=Array("type","<li class=\"on_2\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1400,1507);
$z[12][4]['typeid']="2";
$z[13]=Array("type","<li class=\"on_3\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1519,1626);
$z[13][4]['typeid']="3";
$z[14]=Array("type","<li class=\"on_4\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1638,1745);
$z[14][4]['typeid']="4";
$z[15]=Array("type","<li class=\"on_5\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1757,1864);
$z[15][4]['typeid']="5";
$z[16]=Array("type","[field:ID /]",1933,1968);
$z[17]=Array("type","[field:ID /]",2015,2050);

?>