<?php
$z[0]=Array("type","<li class=\"on_1\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",112,219);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<li class=\"on_2\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",227,334);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<li class=\"on_3\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",342,449);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<li class=\"on_4\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",457,564);
$z[3][4]['typeid']="4";
$z[4]=Array("type","<li class=\"on_5\"><a href=\"[field:typelink /]\">[field:typename /]</a></li>",572,679);
$z[4][4]['typeid']="5";
$z[5]=Array("global","",706,732);
$z[5][4]['name']="cfg_powerby";

?>